#  _____                              _      _____  _                     _____        __
# |  __ \                            (_)    |  __ \| |                   |_   _|      / _|
# | |  | |_   _ _ __   __ _ _ __ ___  _  ___| |__) | | __ _ _   _  ___ _ __| |  _ __ | |_ ___
# | |  | | | | | '_ \ / _` | '_ ` _ \| |/ __|  ___/| |/ _` | | | |/ _ \ '__| | | '_ \|  _/ _ \
# | |__| | |_| | | | | (_| | | | | | | | (__| |    | | (_| | |_| |  __/ | _| |_| | | | || (_) |
# |_____/ \__, |_| |_|\__,_|_| |_| |_|_|\___|_|    |_|\__,_|\__, |\___|_||_____|_| |_|_| \___/
#         __/ |                                             __/ |
#        |___/                                             |___/

# Author: Tedesk
# The default configuration requires Player expansion from PlaceholderAPI installed.

info: "&f%player_name% &7| &f%player_health_rounded% &c❤ &7| %player_colored_ping%ms"
update-time: 0.25 # Measured in seconds.
line-of-sight: 10.0 # Measured in blocks.

plugin:
  admin-permission: "dpi.admin"
messages:
  reloaded: "&aPlugin successfully reloaded"
  without-permission: "&cYou don´t have permission to use this command."
  incompatible:
    - "&cYour server version is behind 1.8!"
    - "&cIf you think this is an error, contact the author &fTedesk"
    - "&cThe plugin will be disabled."
  enabled:
    - "&aPlugin enabled!"
  disabled:
    - "&cPlugin disabled!"
  help:
    - "&bDynamicPlayerInfo &7- Commands"
    - ""
    - "&b/dpi reload &7- &fReloads the configuration of the plugin."